declare const __SERVE_AVD_VERSION__: string | undefined;
declare const __AUTH_FONT_CSS__: string | undefined;

/** Public authentication shell. Device data is only fetched by the workspace. */
export function authPage(basePath: string, returnTo?: string): string {
  const base = JSON.stringify(basePath.replace(/\/$/, "")).replace(/</g, "\\u003c");
  const target = JSON.stringify(returnTo ?? "").replace(/</g, "\\u003c");
  const fonts = typeof __AUTH_FONT_CSS__ === "string" ? __AUTH_FONT_CSS__ : "";
  const version = typeof __SERVE_AVD_VERSION__ === "string" ? __SERVE_AVD_VERSION__ : "dev";
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account · serve-avd</title>
<style>${fonts}
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#101113;color:#eee}*{box-sizing:border-box}body{margin:0}main{width:min(880px,100%);margin:8vh auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:28px}.brand{font-size:20px;font-weight:650}section{background:#191b1e;border:1px solid #34363c;border-radius:16px;padding:28px;margin-bottom:20px}#login{max-width:440px;margin:auto}h1{font-size:25px;margin:0 0 12px}h2{font-size:19px;margin:0 0 18px}p{color:#aaa;line-height:1.5}form{display:grid;gap:16px}label{display:grid;gap:8px;font-size:14px}input,select,button,a.button{font:inherit;border:1px solid #44474f;border-radius:8px;padding:12px;color:#eee;background:#25272c}input,select{width:100%;min-width:0}input:focus-visible,select:focus-visible,button:focus-visible,a:focus-visible{outline:2px solid #a9bfff;outline-offset:3px}button,a.button{cursor:pointer}button.primary{background:#c4d2ff;color:#111;border-color:#c4d2ff;font-weight:600}button:disabled{opacity:.5;cursor:wait}a{color:#c4d2ff}a.button{text-decoration:none;text-align:center}.password{display:flex;gap:8px}.password input{flex:1}.password button{flex-shrink:0}.actions{display:flex;gap:12px;flex-wrap:wrap}.actions>*{flex:1}.status{min-height:1.5em;color:#f9a5a5;white-space:pre-wrap}.status.success{color:#a9d7bb}[hidden]{display:none!important}.user{border-top:1px solid #34363c;padding:20px 0}.user:first-child{border-top:0}.user-title{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-bottom:12px}.user form{grid-template-columns:repeat(2,minmax(0,1fr))}.user .wide{grid-column:1/-1}.hint{font-size:13px;margin:0}.muted{color:#aaa}#identity{color:#bbb}@media(max-width:600px){main{margin:0 auto;padding:16px}section{padding:20px}header{margin:12px 0 24px}.user form{grid-template-columns:1fr}.actions{flex-direction:column}}

/* Login design supplied in Sign in-html.zip; fonts are embedded by the build. */
body.login-view{background:#0D0E10;color:#ECEEF0;font-family:'IBM Plex Sans',system-ui,sans-serif;font-size:14px;min-height:100dvh;display:flex;flex-direction:column}
.auth-header{height:52px;flex-shrink:0;display:flex;align-items:center;gap:8px;padding:0 20px;border-bottom:1px solid #1B1E22;margin:0;justify-content:flex-start}
.auth-header .brand{font-size:14px;font-weight:600}.auth-version{color:#7C838B;font-family:'IBM Plex Mono',monospace;font-size:12px}.auth-header #workspace{margin-left:auto}
.login-view main{flex:1;width:100%;margin:0;display:flex;align-items:center;justify-content:center;padding:48px 16px}
.login-view #login{width:100%;max-width:380px;margin:0;padding:0;border:0;border-radius:0;background:none;display:flex;flex-direction:column;gap:20px}
#login h1{margin:0;font-size:22px;font-weight:600;letter-spacing:-.01em}#login .login-intro{display:grid;gap:6px}#login .login-intro p{margin:0;color:#A3A9B0;line-height:1.5}
#login-form{background:#141619;border:1px solid #262A2F;border-radius:14px;padding:24px;display:flex;flex-direction:column;gap:18px}
#login-form .field{display:flex;flex-direction:column;gap:6px}#login-form label{font-size:13px;font-weight:500;color:#DADDE1;display:block}
#login-form input:not([type=checkbox]){height:44px;padding:0 12px;background:#0F1113;border:1px solid #2C3036;border-radius:8px;color:#ECEEF0;font-size:14px}
#login-form input:focus{outline:none;border-color:#6EE7B7;box-shadow:0 0 0 3px #6ee7b72e}#login-form input[aria-invalid=true]{border-color:#8A3A3D}
#login-form .password{position:relative;display:block}#login-form #login-pass{padding-right:48px}#login-form .reveal{position:absolute;right:4px;top:4px;width:36px;height:36px;display:grid;place-items:center;padding:0;background:transparent;border:0;border-radius:6px;color:#A3A9B0}
#login-form .reveal svg{pointer-events:none}#login-form .eye-off{display:none}#login-form .reveal[aria-pressed=true] .eye{display:none}#login-form .reveal[aria-pressed=true] .eye-off{display:block}
#login-form .remember{display:flex;align-items:center;gap:10px;min-height:28px;color:#C9CED3;font-size:13px;font-weight:400;cursor:pointer}#login-form .remember input{width:16px;height:16px;margin:0;accent-color:#6EE7B7;flex-shrink:0}
#login-form .primary,.session-card .button{height:44px;display:flex;align-items:center;justify-content:center;gap:8px;background:#6EE7B7;color:#06281C;border:0;border-radius:8px;font-size:14px;font-weight:600}
#login-form .primary:disabled{opacity:.75;cursor:progress}#login-form .spinner{display:none;width:16px;height:16px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;animation:spin .8s linear infinite}#login-form[aria-busy=true] .spinner{display:block}
#login-form button:focus-visible,.login-view a:focus-visible{outline:2px solid #6EE7B7;outline-offset:2px}
#login .recovery{margin:0;text-align:center;font-size:12px;color:#7C838B;line-height:1.6}
.field-error{font-size:12px;color:#F2777A}.caps-hint{font-size:12px;color:#F5B544}
#login-form #status{margin:0;min-height:0;padding:10px 12px;background:#2A1719;border:1px solid #4A2E30;border-radius:8px;color:#F6A5A7;font-size:13px;line-height:1.45}#status:empty{display:none}
.session-card{width:100%;max-width:380px;background:#141619;border:1px solid #262A2F;border-radius:14px;padding:28px 24px;display:flex;flex-direction:column;gap:14px;align-items:flex-start}.session-card h1{font-size:18px;margin:0}.session-card .button{width:100%}.session-card button{align-self:center;background:transparent;border:0;color:#A3A9B0;font-size:13px;padding:8px}.session-check{width:36px;height:36px;border-radius:50%;background:#22352C;color:#6EE7B7;display:grid;place-items:center}
@keyframes spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){#login-form .spinner{animation:none}}
@media(max-width:600px){.auth-header{margin:0}.login-view main{padding:32px 16px}#login-form input:not([type=checkbox]){font-size:16px}}
</style></head><body class="login-view"><header class="auth-header"><svg width="14" height="14" viewBox="0 0 24 24" fill="#6EE7B7" aria-hidden="true"><path d="M6 4l14 8-14 8z"/></svg><span class="brand">serve-avd</span><span class="auth-version">v${version}</span><a id="workspace" hidden>Workspace</a></header><main>
<section id="login" hidden>
<div class="login-intro"><h1>Sign in</h1><p>This host streams Android emulators. Sign in to view and control them.</p></div>
<form id="login-form" novalidate>
<div class="field"><label for="login-user">Username</label><input id="login-user" name="username" autocomplete="username" autocapitalize="none" spellcheck="false" required maxlength="64" aria-describedby="user-error" autofocus><span id="user-error" class="field-error" hidden>Enter your username</span></div>
<div class="field"><label for="login-pass">Password</label><div class="password"><input id="login-pass" name="password" type="password" autocomplete="current-password" required aria-describedby="pass-error caps-hint"><button type="button" class="reveal" aria-label="Show password" aria-pressed="false"><svg class="eye" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></svg><svg class="eye-off" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M3 3l18 18M10.6 5.1A10 10 0 0 1 12 5c6.5 0 10 7 10 7a17 17 0 0 1-3.2 4M6.6 6.6C3.8 8.3 2 12 2 12s3.5 7 10 7c1.8 0 3.3-.5 4.6-1.3"/></svg></button></div><span id="pass-error" class="field-error" hidden>Enter your password</span><span id="caps-hint" class="caps-hint" hidden>Caps Lock is on</span></div>
<label class="remember"><input type="checkbox" name="remember" checked>Keep me signed in on this browser</label>
<button class="primary" type="submit"><span class="spinner" aria-hidden="true"></span><span id="submit-label">Sign in</span></button>
</form><p class="recovery">Forgot your password? Ask the person who runs this host to reset it.</p>
</section>
<section id="signed-in" class="session-card" hidden><span class="session-check" aria-hidden="true">✓</span><h1 id="signed-in-name"></h1><a id="open-workspace" class="button">Open workspace</a><button id="different-account" type="button">Use a different account</button></section>
<section id="account" hidden><h1>Your account</h1><p id="identity"></p><p id="forced" hidden>You must change your password before opening the workspace.</p><h2>Change password</h2><form id="password-form"><label>Current password<span class="password"><input name="currentPassword" type="password" autocomplete="current-password" required><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></span></label><label>New password<span class="password"><input name="newPassword" type="password" autocomplete="new-password" required minlength="15" maxlength="256" aria-describedby="password-policy"><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></span></label><p id="password-policy" class="hint">Use 15–128 characters. Spaces and password-manager paste are welcome.</p><label>Confirm new password<input name="confirmPassword" type="password" autocomplete="new-password" required></label><button class="primary" type="submit">Change password</button></form><div class="actions" style="margin-top:20px"><button id="logout" type="button">Sign out</button></div></section>
<section id="admin" hidden><h2>Manage accounts</h2><p>New and reset passwords must be changed at next sign in.</p><form id="create-form"><label>Username<input name="username" autocomplete="off" required maxlength="64"></label><label>Temporary password<span class="password"><input name="password" type="password" autocomplete="new-password" required minlength="15" maxlength="256"><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></span></label><label>Role<select name="role"><option value="operator">Operator</option><option value="admin">Administrator</option></select></label><button class="primary" type="submit">Create account</button></form><h2 style="margin-top:28px">Accounts</h2><div id="users"></div><button id="refresh-users" type="button">Refresh accounts</button></section>
<p id="status" class="status" role="status" aria-live="polite" tabindex="-1"></p></main>
<script>
'use strict';
const base=${base};
const initialReturn=${target};
const $=id=>document.getElementById(id);
let me=null, csrf='';
function returnPath(){const value=new URLSearchParams(location.search).get('returnTo')||initialReturn||base+'/';try{const url=new URL(value,location.origin);if(url.origin===location.origin&&url.pathname.startsWith(base+'/')&&!url.pathname.startsWith(base+'/auth/')&&url.pathname.slice(base.length)!=='/login')return url.pathname+url.search+url.hash;}catch{}return base+'/';}
function message(text,ok=false){$('status').textContent=text;$('status').classList.toggle('success',ok);}
async function request(path,body){const options={credentials:'same-origin',headers:{}};if(body!==undefined){options.method='POST';options.headers={'Content-Type':'application/json','X-CSRF-Token':csrf};options.body=JSON.stringify(body);}const response=await fetch(base+'/auth/'+path,options);let data={};try{data=await response.json();}catch{}if(!response.ok){if(response.status===401&&path!=='login'){me=null;csrf='';render();}throw new Error(path==='login'?(response.status===429?'Too many attempts. Try again later.':'Invalid username or password.'):(data.error||'Request failed. Please try again.'));}return data;}
function render(){const signed=!!me;const welcome=signed&&!me.mustChangePassword&&location.pathname===base+'/login';document.body.classList.toggle('login-view',!signed||welcome);$('signed-in').hidden=!welcome;if(welcome){$('signed-in-name').textContent='Signed in as '+me.username;$('open-workspace').href=returnPath();}$('status').setAttribute('role',signed?'status':'alert');if(!signed)$('login-form').prepend($('status'));else document.querySelector('main').append($('status'));$('login').hidden=signed;$('account').hidden=!signed||welcome;$('admin').hidden=!signed||welcome||me.role!=='admin'||me.mustChangePassword;$('workspace').hidden=!signed||me.mustChangePassword;$('workspace').href=returnPath();$('forced').hidden=!signed||!me.mustChangePassword;if(signed)$('identity').textContent=me.username+' · '+(me.role==='admin'?'Administrator':'Operator');}
async function loadMe(){try{const data=await request('me');me=data.user;csrf=data.csrfToken;render();if(me&&!me.mustChangePassword&&me.role==='admin'&&location.pathname!==base+'/login')await loadUsers();}catch(error){render();if(me)message(error.message);}}
function reveal(button){const input=button.previousElementSibling;const show=input.type==='password';input.type=show?'text':'password';if(!button.querySelector('svg'))button.textContent=show?'Hide':'Show';button.setAttribute('aria-label',show?'Hide password':'Show password');button.setAttribute('aria-pressed',String(show));}
document.addEventListener('click',event=>{const button=event.target.closest('.reveal');if(button)reveal(button);});
async function busy(form,task){const buttons=Array.from(form.querySelectorAll('button'));buttons.forEach(b=>b.disabled=true);form.setAttribute('aria-busy','true');message('');try{await task();}catch(error){message(error.message);$('status').focus();}finally{buttons.forEach(b=>b.disabled=false);form.removeAttribute('aria-busy');}}
function validateLogin(){let valid=true;for(const [id,error] of [['login-user','user-error'],['login-pass','pass-error']]){const input=$(id);const missing=id==='login-user'?!input.value.trim():!input.value;input.setAttribute('aria-invalid',String(missing));$(error).hidden=!missing;if(missing)valid=false;}return valid;}
for(const id of ['login-user','login-pass'])$(id).addEventListener('input',()=>{message('');if($(id).getAttribute('aria-invalid')==='true')validateLogin();});
$('login-pass').addEventListener('keyup',event=>{$('caps-hint').hidden=!event.getModifierState('CapsLock');});
$('login-pass').addEventListener('blur',()=>{$('caps-hint').hidden=true;});
$('login-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;if(form.getAttribute('aria-busy')==='true')return;if(!validateLogin()){form.querySelector('[aria-invalid=true]').focus();return;}void busy(form,async()=>{const data=new FormData(form);$('submit-label').textContent='Signing in…';try{await request('login',{username:data.get('username'),password:data.get('password'),remember:data.has('remember')});form.reset();const identity=await request('me');location.assign(identity.user.mustChangePassword?base+'/account?returnTo='+encodeURIComponent(returnPath()):returnPath());}finally{$('submit-label').textContent='Sign in';}});};
$('different-account').onclick=()=>void busy($('signed-in'),async()=>{await request('logout',{});location.assign(base+'/login');});
$('password-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;void busy(form,async()=>{const data=new FormData(form);const next=data.get('newPassword');if(next!==data.get('confirmPassword'))throw new Error('New passwords do not match.');if(Array.from(next).length<15||Array.from(next).length>128)throw new Error('Use a password of 15–128 characters.');const forced=me.mustChangePassword;await request('password',{currentPassword:data.get('currentPassword'),newPassword:next});form.reset();await loadMe();if(forced)location.assign(returnPath());else message('Password changed. Other sessions have been signed out.',true);});};
$('logout').onclick=()=>void busy($('account'),async()=>{await request('logout',{});location.assign(base+'/login');});
$('create-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;void busy(form,async()=>{const data=Object.fromEntries(new FormData(form));await request('users',data);form.reset();await loadUsers();message('Account created. The temporary password must be changed at sign in.',true);});};
function node(tag,text){const el=document.createElement(tag);if(text)el.textContent=text;return el;}
async function loadUsers(){const data=await request('users');$('users').replaceChildren();for(const user of data.users){const row=node('div');row.className='user';const title=node('div');title.className='user-title';title.append(node('strong',user.username),node('span',user.role+' · '+(user.enabled?'Enabled':'Disabled')+(user.mustChangePassword?' · Password change required':'')));row.append(title);const form=node('form');const label=node('label','Action');const action=node('select');action.name='action';for(const [value,text]of [['password','Reset password'],['enabled',user.enabled?'Disable account':'Enable account'],['role','Change role'],['revoke','Revoke all sessions']]){const option=node('option',text);option.value=value;action.append(option);}label.append(action);const valueLabel=node('label','Temporary password');const password=node('input');password.type='password';password.autocomplete='new-password';password.minLength=15;password.maxLength=256;password.required=true;valueLabel.append(password);const role=node('select');for(const value of ['operator','admin']){const option=node('option',value==='admin'?'Administrator':'Operator');option.value=value;role.append(option);}role.value=user.role;role.hidden=true;valueLabel.append(role);const submit=node('button','Reset password');submit.type='submit';submit.className='wide';form.append(label,valueLabel,submit);action.onchange=()=>{password.hidden=action.value!=='password';password.required=action.value==='password';password.value='';role.hidden=action.value!=='role';valueLabel.hidden=!['password','role'].includes(action.value);valueLabel.firstChild.textContent=action.value==='role'?'Role':'Temporary password';submit.textContent=action.selectedOptions[0].textContent;};form.onsubmit=event=>{event.preventDefault();void busy(form,async()=>{const kind=action.value;const body=kind==='password'?{password:password.value}:kind==='enabled'?{enabled:!user.enabled}:kind==='role'?{role:role.value}:{};await request('users/'+encodeURIComponent(user.id)+'/'+kind,body);password.value='';await loadMe();message('Account updated.',true);});};row.append(form);$('users').append(row);}}
$('refresh-users').onclick=()=>void busy($('admin'),loadUsers);
void loadMe();
</script></body></html>`;
}
