/** Public authentication shell. Device data is only fetched by the workspace. */
export function authPage(basePath: string, returnTo?: string): string {
  const base = JSON.stringify(basePath.replace(/\/$/, "")).replace(/</g, "\\u003c");
  const target = JSON.stringify(returnTo ?? "").replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account · serve-avd</title>
<style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#101113;color:#eee}*{box-sizing:border-box}body{margin:0}main{width:min(880px,100%);margin:8vh auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:28px}.brand{font-size:20px;font-weight:650}section{background:#191b1e;border:1px solid #34363c;border-radius:16px;padding:28px;margin-bottom:20px}#login{max-width:440px;margin:auto}h1{font-size:25px;margin:0 0 12px}h2{font-size:19px;margin:0 0 18px}p{color:#aaa;line-height:1.5}form{display:grid;gap:16px}label{display:grid;gap:8px;font-size:14px}input,select,button,a.button{font:inherit;border:1px solid #44474f;border-radius:8px;padding:12px;color:#eee;background:#25272c}input,select{width:100%;min-width:0}input:focus-visible,select:focus-visible,button:focus-visible,a:focus-visible{outline:2px solid #a9bfff;outline-offset:3px}button,a.button{cursor:pointer}button.primary{background:#c4d2ff;color:#111;border-color:#c4d2ff;font-weight:600}button:disabled{opacity:.5;cursor:wait}a{color:#c4d2ff}a.button{text-decoration:none;text-align:center}.password{display:flex;gap:8px}.password input{flex:1}.password button{flex-shrink:0}.actions{display:flex;gap:12px;flex-wrap:wrap}.actions>*{flex:1}.status{min-height:1.5em;color:#f9a5a5;white-space:pre-wrap}.status.success{color:#a9d7bb}[hidden]{display:none!important}.user{border-top:1px solid #34363c;padding:20px 0}.user:first-child{border-top:0}.user-title{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-bottom:12px}.user form{grid-template-columns:repeat(2,minmax(0,1fr))}.user .wide{grid-column:1/-1}.hint{font-size:13px;margin:0}.muted{color:#aaa}#identity{color:#bbb}@media(max-width:600px){main{margin:0 auto;padding:16px}section{padding:20px}header{margin:12px 0 24px}.user form{grid-template-columns:1fr}.actions{flex-direction:column}}
</style></head><body><main><header><span class="brand">▶ serve-avd</span><a id="workspace" hidden>Workspace</a></header>
<section id="login" hidden><h1>Sign in</h1><p>Use your account to open the device workspace.</p><form id="login-form"><label>Username<input name="username" autocomplete="username" required maxlength="64" autofocus></label><label>Password<span class="password"><input name="password" type="password" autocomplete="current-password" required><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></span></label><button class="primary" type="submit">Sign in</button></form></section>
<section id="account" hidden><h1>Your account</h1><p id="identity"></p><p id="forced" hidden>You must change your password before opening the workspace.</p><h2>Change password</h2><form id="password-form"><label>Current password<span class="password"><input name="currentPassword" type="password" autocomplete="current-password" required><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></span></label><label>New password<span class="password"><input name="newPassword" type="password" autocomplete="new-password" required minlength="15" maxlength="256" aria-describedby="password-policy"><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></span></label><p id="password-policy" class="hint">Use 15–128 characters. Spaces and password-manager paste are welcome.</p><label>Confirm new password<input name="confirmPassword" type="password" autocomplete="new-password" required></label><button class="primary" type="submit">Change password</button></form><div class="actions" style="margin-top:20px"><button id="logout" type="button">Sign out</button></div></section>
<section id="admin" hidden><h2>Manage accounts</h2><p>New and reset passwords must be changed at next sign in.</p><form id="create-form"><label>Username<input name="username" autocomplete="off" required maxlength="64"></label><label>Temporary password<span class="password"><input name="password" type="password" autocomplete="new-password" required minlength="15" maxlength="256"><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></span></label><label>Role<select name="role"><option value="operator">Operator</option><option value="admin">Administrator</option></select></label><button class="primary" type="submit">Create account</button></form><h2 style="margin-top:28px">Accounts</h2><div id="users"></div><button id="refresh-users" type="button">Refresh accounts</button></section>
<p id="status" class="status" role="status" aria-live="polite" tabindex="-1"></p></main>
<script>
'use strict';
const base=${base};
const initialReturn=${target};
const $=id=>document.getElementById(id);
let me=null, csrf='';
function returnPath(){const value=new URLSearchParams(location.search).get('returnTo')||initialReturn||base+'/';try{const url=new URL(value,location.origin);if(url.origin===location.origin&&url.pathname.startsWith(base+'/')&&!url.pathname.startsWith(base+'/auth/')&&url.pathname.slice(base.length)!=='/login')return url.pathname+url.search+url.hash;}catch{}return base+'/';}
function message(text,ok=false){$('status').textContent=text;$('status').classList.toggle('success',ok);}
async function request(path,body){const options={credentials:'same-origin',headers:{}};if(body!==undefined){options.method='POST';options.headers={'Content-Type':'application/json','X-CSRF-Token':csrf};options.body=JSON.stringify(body);}const response=await fetch(base+'/auth/'+path,options);let data={};try{data=await response.json();}catch{}if(!response.ok){if(response.status===401&&path!=='login'){me=null;csrf='';render();}throw new Error(path==='login'?(response.status===429?'Too many attempts. Try again later.':'Invalid username or password.'):(data.error||'Request failed. Please try again.'));}return data;}
function render(){const signed=!!me;$('login').hidden=signed;$('account').hidden=!signed;$('admin').hidden=!signed||me.role!=='admin'||me.mustChangePassword;$('workspace').hidden=!signed||me.mustChangePassword;$('workspace').href=returnPath();$('forced').hidden=!signed||!me.mustChangePassword;if(signed)$('identity').textContent=me.username+' · '+(me.role==='admin'?'Administrator':'Operator');}
async function loadMe(){try{const data=await request('me');me=data.user;csrf=data.csrfToken;render();if(me&&!me.mustChangePassword&&me.role==='admin')await loadUsers();}catch(error){render();if(me)message(error.message);}}
function reveal(button){const input=button.previousElementSibling;const show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'Hide':'Show';button.setAttribute('aria-label',show?'Hide password':'Show password');button.setAttribute('aria-pressed',String(show));}
document.addEventListener('click',event=>{if(event.target.matches('.reveal'))reveal(event.target);});
async function busy(form,task){const buttons=Array.from(form.querySelectorAll('button'));buttons.forEach(b=>b.disabled=true);form.setAttribute('aria-busy','true');message('');try{await task();}catch(error){message(error.message);$('status').focus();}finally{buttons.forEach(b=>b.disabled=false);form.removeAttribute('aria-busy');}}
$('login-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;void busy(form,async()=>{const data=new FormData(form);await request('login',{username:data.get('username'),password:data.get('password')});form.reset();const identity=await request('me');location.assign(identity.user.mustChangePassword?base+'/account?returnTo='+encodeURIComponent(returnPath()):returnPath());});};
$('password-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;void busy(form,async()=>{const data=new FormData(form);const next=data.get('newPassword');if(next!==data.get('confirmPassword'))throw new Error('New passwords do not match.');if(Array.from(next).length<15||Array.from(next).length>128)throw new Error('Use a password of 15–128 characters.');const forced=me.mustChangePassword;await request('password',{currentPassword:data.get('currentPassword'),newPassword:next});form.reset();await loadMe();if(forced)location.assign(returnPath());else message('Password changed. Other sessions have been signed out.',true);});};
$('logout').onclick=()=>void busy($('account'),async()=>{await request('logout',{});location.assign(base+'/login');});
$('create-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;void busy(form,async()=>{const data=Object.fromEntries(new FormData(form));await request('users',data);form.reset();await loadUsers();message('Account created. The temporary password must be changed at sign in.',true);});};
function node(tag,text){const el=document.createElement(tag);if(text)el.textContent=text;return el;}
async function loadUsers(){const data=await request('users');$('users').replaceChildren();for(const user of data.users){const row=node('div');row.className='user';const title=node('div');title.className='user-title';title.append(node('strong',user.username),node('span',user.role+' · '+(user.enabled?'Enabled':'Disabled')+(user.mustChangePassword?' · Password change required':'')));row.append(title);const form=node('form');const label=node('label','Action');const action=node('select');action.name='action';for(const [value,text]of [['password','Reset password'],['enabled',user.enabled?'Disable account':'Enable account'],['role','Change role'],['revoke','Revoke all sessions']]){const option=node('option',text);option.value=value;action.append(option);}label.append(action);const valueLabel=node('label','Temporary password');const password=node('input');password.type='password';password.autocomplete='new-password';password.minLength=15;password.maxLength=256;password.required=true;valueLabel.append(password);const role=node('select');for(const value of ['operator','admin']){const option=node('option',value==='admin'?'Administrator':'Operator');option.value=value;role.append(option);}role.value=user.role;role.hidden=true;valueLabel.append(role);const submit=node('button','Reset password');submit.type='submit';submit.className='wide';form.append(label,valueLabel,submit);action.onchange=()=>{password.hidden=action.value!=='password';password.required=action.value==='password';password.value='';role.hidden=action.value!=='role';valueLabel.hidden=!['password','role'].includes(action.value);valueLabel.firstChild.textContent=action.value==='role'?'Role':'Temporary password';submit.textContent=action.selectedOptions[0].textContent;};form.onsubmit=event=>{event.preventDefault();void busy(form,async()=>{const kind=action.value;const body=kind==='password'?{password:password.value}:kind==='enabled'?{enabled:!user.enabled}:kind==='role'?{role:role.value}:{};await request('users/'+encodeURIComponent(user.id)+'/'+kind,body);password.value='';await loadMe();message('Account updated.',true);});};row.append(form);$('users').append(row);}}
$('refresh-users').onclick=()=>void busy($('admin'),loadUsers);
void loadMe();
</script></body></html>`;
}
